src/Entity/Trick.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\TrickRepository;
use App\EventListener;
use App\EventListener\TrickListener;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[ORM\Table(name: "st_trick")]
#[UniqueEntity('name', message: "Name is arlready exist")]
class Trick
{
    #[ORM\Id()]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column(type: "integer")]
    private int $id;

    #[ORM\Column(length: 200, type: "string", unique: true)]
    private string $name;

    #[ORM\Column(length: 5000, type: Types::TEXT)]
    private string $description;

    #[ORM\Column(length: 255, type: "string", unique: true)]
    private ?string $slug = null;

    #[ORM\Column(type: "datetime")]
    private datetime $created_at;

    #[ORM\Column(type: "datetime")]
    private datetime $modified_at;

    #[ORM\Column(type: "datetime", nullable: true)]
    private datetime $deleted_at;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Picture::class, cascade: ['persist'])]
    private Collection $pictures;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class, cascade: ['persist'])]
    private Collection $videos;

    #[ORM\ManyToOne(inversedBy: 'tricks', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?TrickGroup $trick_group = null;



    public function __construct()
    {

        $utc_timezone = new \DateTimeZone("Europe/Paris");
        $date = new \DateTime("now", $utc_timezone);

        $this->setCreatedAt($date);
        $this->setModifiedAt($date);
        $this->pictures = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
    }

    public function getModifiedAt()
    {
        return $this->modified_at;
    }

    public function setModifiedAt($modified_at)
    {
        $this->modified_at = $modified_at;
    }

    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): static
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): static
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getTrickGroup(): ?TrickGroup
    {
        return $this->trick_group;
    }

    public function setTrickGroup(?TrickGroup $trick_group): static
    {
        $this->trick_group = $trick_group;

        return $this;
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Service\AuthorizedService;
use App\Entity\Picture;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\TrickType;
use App\Entity\Trick;
use App\Entity\Video;
use App\Form\CommentFormType;
use App\Service\PictureService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\String\Slugger\SluggerInterface;

class TrickController extends AbstractController
{

    protected $slugger;

    public function __construct(SluggerInterface $slugger)
    {
        $this->slugger = $slugger;
    }

    #[Route('/trick/new', name: 'createTrick')]
    public function new(Request $request, EntityManagerInterface $entityManager, PictureService $pictureService, AuthorizedService $authorizedService)
    {
        if ($authorizedService->isAuthorizedUserAndVerified($this->getUser()) === true) {

            $trick = new Trick();


            $form = $this->createForm(TrickType::class, $trick);
            $form->remove('image');
            $form->handleRequest($request);


            if ($form->isSubmitted() && $form->isValid()) {

                /* Get all input pictures */
                $images = $form->get('images')->getData();

                foreach ($images as $image) {
                    /* Destination folder */
                    $folder = 'tricks';

                    $fichier = $pictureService->add($image, $folder, 300, 300);

                    $picture = new Picture();
                    $picture->setTrick($trick);
                    $picture->setName($fichier);
                    $trick->addPicture($picture);
                }
                $trick->setSlug($this->slugger->slug(strtolower($trick->getName())));
                $entityManager->persist($trick);
                $entityManager->flush();
                $this->addFlash('success', 'the new trick has been correctly added');
                return $this->redirect($this->generateUrl('index') . '#tricks-homepage');
            }



            return $this->render('trick/new.html.twig', array(
                'form' => $form->createView(),
            ));
        }
        $this->addFlash('danger', 'You need to be connected and verified user to add a new tricks');
        return $this->redirectToRoute('app_login');
    }

    #[Route('/', name: 'index')]
    public function index(EntityManagerInterface $entityManager)
    {
        $repository = $entityManager->getRepository(Trick::class);
        $repositoryPicture = $entityManager->getRepository(Picture::class);
        $page = 1;
        $all_tricks_count = (int)ceil($repository->getAllTricksCount() / 15);
        $tricks = $repository->findByLimitTrick($page)->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        foreach ($tricks as $id => $trick) {
            $image = $repositoryPicture->onePictureByTrickId($trick['id']);
            if ($image) {
                $trick['image'] = $image[0]['name'];
                $tricks[$id] = $trick;
            }
        }
        return $this->render('index.html.twig', array("tricks" => $tricks, 'number_page' => $all_tricks_count));
    }

    #[Route('/trick/{slug}', name: 'trick')]
    public function trick(EntityManagerInterface $entityManager, Request $request, string $slug, AuthorizedService $authorizedService)
    {

        $slug = $request->attributes->get('slug');

        $repository = $entityManager->getRepository(Trick::class);
        $trick = $repository->findOneBySomeField($slug);

        $trickId = $trick->getId();

        $repositoryImage = $entityManager->getRepository((Picture::class));
        $images = $repositoryImage->findByTrickId($trickId);

        $repositoryVideo = $entityManager->getRepository((Video::class));
        $videos = $repositoryVideo->findByTrickId($trickId);

        $repositoryComment = $entityManager->getRepository((Comment::class));

        $page = 1;
        $all_comments_count = $repositoryComment->getAllCommentCount($trickId) / 10;
        $comments = $repositoryComment->findByLimitComment($page, $trickId)->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);


        $form = $this->createForm(CommentFormType::class);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            if ($authorizedService->isAuthorizedUserAndVerified($this->getUser()) === false) {
                $this->addFlash('warning', 'You need to be connected and have a verified account to leave a comment');
                return $this->redirectToRoute('trick', array('slug' => $trick->getSlug()));
            }

            $comment = new Comment();
            $comment->setUser($this->getUser());
            $comment->setContent($form->get('content')->getData());
            $comment->setTrick($trick);
            $entityManager->persist($comment);
            $entityManager->flush();
            $this->addFlash('success', 'the new comment has been correctly added');
            return $this->redirectToRoute('trick', array('slug' => $trick->getSlug()));
        }

        return $this->render('trick/trick.html.twig', array("trick" => $trick, 'images' => $images, 'videos' => $videos, 'comments' => $comments, 'number_page' => $all_comments_count, 'form' => $form));
    }


    #[Route('/trick/page/{page}', name: 'getTricksPaged')]
    public function getTricksPaged(EntityManagerInterface $entityManager, Request $request, AuthorizedService $authorizedService)
    {
        $repository = $entityManager->getRepository(Trick::class);
        $page = $request->attributes->get('page');
        $repositoryPicture = $entityManager->getRepository(Picture::class);
        $tricks = $repository->findByLimitTrick($page);
        $response = $tricks->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        $exitall = array();


        foreach ($response as $key) {

            if ($key && is_array($key) === true) {
                $image = $repositoryPicture->onePictureByTrickId($key['id']);
                
                $exit = "
            <div class='trick-teaser col-12 col-sm-6 col-md-6'>";
                if ($image) {
                    $exit .= '<img src="assets/img/tricks/mini/300x300-' . $image[0]["name"] . '">';
                } else {
                    $exit .= '<img src="assets/img/tricks/default.webp">';
                }
                $exit .= "<a class='name h3_style' href='" . $this->generateUrl('trick', array('slug' => $key['slug'])) . "'>
                    <h2>" . $key['name'] . "</h2>
                </a>";
                if ($authorizedService->isAuthorizedUserAndVerified($this->getUser()) === true) {
                    $exit .=
                        "<div class='modify-panel'>
                    <a href='" . $this->generateUrl('modifyTrick', array('slug' => $key['slug'])) . "'>
                        <img class='icon' src='/assets/img/svg/crayon.svg'>
                    </a>

                    <span class='open-modal' data-url='" . $this->generateUrl('deleteTrick', array('slug' => $key['slug']))  . "'>
                        <img class='icon' src='/assets/img/svg/trash.svg'>
                    </span>
                    
                </div>";
                }
                $exit .= "</div>";

                $exitall[] = $exit;
            }
        }

        return new JsonResponse($exitall);
    }

    #[Route('/trick/modify/{slug}', name: 'modifyTrick')]
    public function modifyTrick(EntityManagerInterface $entityManager, Request $request, string $slug, PictureService $pictureService, AuthorizedService $authorizedService)
    {

        if ($authorizedService->isAuthorizedUserAndVerified($this->getUser()) === true) {
            $slug = $request->attributes->get('slug');

            $repository = $entityManager->getRepository(Trick::class);

            $trick = $repository->findOneBySomeField($slug);

            $trickId = $trick->getId();

            $repositoryImage = $entityManager->getRepository((Picture::class));
            $images = $repositoryImage->findByTrickId($trickId);

            $repositoryVideo = $entityManager->getRepository((Video::class));
            $videos = $repositoryVideo->findByTrickId($trickId);

            $form = $this->createForm(TrickType::class, $trick);
            $form->handleRequest($request);


            if ($form->isSubmitted() && $form->isValid()) {

                /* Get all input pictures */
                $images = $form->get('images')->getData();

                foreach ($images as $image) {
                    /* Destination folder */
                    $folder = 'tricks';

                    $fichier = $pictureService->add($image, $folder, 300, 300);

                    $picture = new Picture();
                    $picture->setTrick($trick);
                    $picture->setName($fichier);
                    $trick->addPicture($picture);
                }
                $trick->setSlug($this->slugger->slug(strtolower($trick->getName())));
                $entityManager->flush();
                $this->addFlash('success', 'Trick has been correctly modified');
                return $this->redirectToRoute('trick', array('slug' => $trick->getSlug()));
            }

            return $this->render(
                'trick/modify.html.twig',
                array(
                    "trick" => $trick,
                    'form' => $form,
                    "images" => $images,
                    "videos" => $videos,
                )
            );
        }
        $this->addFlash('danger', 'You need to be connected and verified user to modify a trick');
        return $this->redirectToRoute('app_login');
    }

    #[Route('/trick/delete/{slug}', name: 'deleteTrick')]

templates/trick/modify.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modify trick
{% endblock %}

{% block body %}

	<div class="trick-single">
		{{ form_start(form, {
                    'attr': {
                        'novalidate': 'novalidate',
                        'class': 'col-lg-5',
                        'id': 'trick-modify-form'
                        }
                    })
                }}
		<div class="hero inmodifie">
			<div class="content">
				<div class="hero_background"></div>
				<div class="text_hero column flex position-absolute">
					<h1 class="title">
						{{trick.name}}
					</h1>
					<div class="input">
						<div class="modify text-center">
							<img class="icon white" src="{{asset('assets/img/svg/crayon.svg')}}">
						</div>
					</div>
				</div>
				{% if images.0 is defined %}
					<img class="primary-image-hero" src="{{asset('assets/img/tricks/')}}{{images.0.name}}" alt="">
				{% else %}
					<img class="primary-image-hero" src="{{asset('assets/img/default.jpg')}}" alt="">
				{% endif %}


			</div>

			<div class="input-form trick-name-input">
				<label for="trick_name">Trick name</label>
				{{ form_widget(form.name) }}
				{{ form_errors(form.name) }}
				<div class="close-form btn btn-dark" data-close>
					Close
				</div>
			</div>

			{% if images.0 is defined %}
				<div class="container-panel position-absolute">
					<a href="{{path('modifyTrickImage', {id: images.0.id})}}" class="modify primary-image" data-modify-picture data-image-id="{{images.0.id}}"><img class="icon white" src="{{asset('assets/img/svg/crayon.svg')}}"></a>
					<a href="{{path('deleteTrickImage', {id: images.0.id})}}" class="delete"><img class="icon white" src="{{asset('assets/img/svg/trash.svg')}}" data-delete data-token="{{csrf_token('delete' ~ images.0.id )}}"></a>
				</div>
			{% endif %}

		</div>
		<div class="container">

			<div class="see_media btn-primary btn">
				See medias
			</div>

			<div class="no_see_media btn-primary btn">
				Hide medias
			</div>

			<div class="gallery">
				{% if images %}
					{% for image in images %}
						{% if loop.index != 1 %}
							<span class="image">
								<img class="image-visual" src="{{asset('assets/img/tricks/mini/300x300-')}}{{image.name}}" alt="" srcset="">
								<a href="{{path('modifyTrickImage', {id: image.id})}}" class="modify" data-modify-picture data-image-id="{{image.id}}"><img class="icon white" src="{{asset('assets/img/svg/crayon.svg')}}"></a>
								<a href="{{path('deleteTrickImage', {id: image.id})}}" class="delete"><img class="icon white" src="{{asset('assets/img/svg/trash.svg')}}" data-delete data-token="{{csrf_token('delete' ~ image.id )}}"></a>
							</span>
						{% endif %}
					{% endfor %}
				{% endif %}


				{% for video in videos %}
					<span class="video" data-index="{{loop.index - 1}}">
						{{video.embed|raw}}
						<span class="modify" data-modify-video><img class="icon white" src="{{asset('assets/img/svg/crayon.svg')}}"></span>
						<a href="{{path('deleteTrickVideo', {id: video.id})}}" class="delete"><img class="icon white" src="{{asset('assets/img/svg/trash.svg')}}" data-delete-video data-token="{{csrf_token('delete' ~ video.id )}}"></a>
					</span>
				{% endfor %}

			</div>

			<div class="input">
				<label for="images">Trick images :
				</label>
				{{ form_widget(form.images) }}
				{{ form_errors(form.images) }}
			</div>

			<div id="videos" class="py-3" data-prototype="{{form_row(form.videos.vars.prototype)|e('html_attr') }}">
				{{form_row(form.videos)}}
				<span></span>
			</div>

			<div class="input">
				<label for="trick_description">Trick description</label>
				{{ form_widget(form.description) }}
				{{ form_errors(form.description) }}
			</div>

			<div class="input">
				<label for="trick_group">Trick group :
				</label>
				{{ form_widget(form.trickGroup) }}
				{{ form_errors(form.trickGroup) }}
			</div>

			<div class="input modify-image-form">
				<label for="trick_group">Trick image modify :
				</label>
				{{ form_widget(form.image) }}
				{{ form_errors(form.image) }}
				<div class="btn btn-primary" data-save-picture>Change</div>
				<div class="btn btn-dark" data-close-modify>Cancel</div>
			</div>

			<div class="input py-5 text-end">
				{{ form_widget(form.save) }}
				<span class="open-modal" data-url={{path('deleteTrick',{slug:trick.slug} )}}>
					<span class="btn btn-danger">Delete</span>
				</span>
			</div>

			{{ form_end(form) }}
		</div>
	</div>
	{% include 'component/modal.html.twig'%}
	{% include 'component/modal_image.html.twig' with {data_to_delete:'data-delete-image', text:'Are you sure to delete this image ?', del_btn_text:'Delete image', cancel_btn_text:'Cancel'} %}
	{% include 'component/modal_image.html.twig' with {data_to_delete:'data-delete-video-trick', text:'Are you sure to delete this video ?', del_btn_text:'Delete video', cancel_btn_text:'Cancel'} %}
{% endblock %}

{% block javascripts %}
	<script src="{{asset('assets/js/form.js')}}"></script>
	<script src="{{asset('assets/js/image.js')}}" defer></script>
{% endblock %}

templates/trick/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Add new trick
{% endblock %}

{% block body %}
	<div class="container">
		{{ form_start(form, {
                    'attr': {
                        'novalidate': 'novalidate',
                        'class': 'col-lg-12'
                        }
                    })
                }}
		<div class="container">
			<div class="input">
				<label for="trick_name">Trick name</label>
				{{ form_widget(form.name) }}
				{{ form_errors(form.name) }}
			</div>

			<div class="input">
				<label for="trick_description">Trick description</label>
				{{ form_widget(form.description) }}
				{{ form_errors(form.description) }}
			</div>

			<div class="input">
				<label for="trick_group">Trick group :
				</label>
				{{ form_widget(form.trickGroup) }}
				{{ form_errors(form.trickGroup) }}
			</div>

			<div class="input">
				<label for="images">Trick images :
				</label>
				{{ form_widget(form.images) }}
				{{ form_errors(form.images) }}
			</div>

			<div id="videos" class="py-3" data-prototype="{{form_row(form.videos.vars.prototype)|e('html_attr') }}">
				{{form_row(form.videos)}}
				<span></span>
			</div>

			<div class="input save">
				{{form_row(form.save)}}
			</div>

			{{ form_end(form) }}
		</div>
	</div>

{% endblock %}

{% block javascripts %}
	<script src="{{asset('assets/js/form.js')}}"></script>
{% endblock %}

templates/trick/trick.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{trick.name}}
{% endblock %}

{% block body %}

	<div class="trick-single">
		<div class="hero">
			<div class="content">
				<div class="hero_background"></div>
				<div class="text_hero column flex position-absolute">
					<h1 class="title">
						{{trick.name}}
					</h1>
				</div>
				{% if images %}
					<img src="{{asset('assets/img/tricks/')}}{{images.0.name}}" alt="">
				{% else %}
					<img src="{{asset('assets/img/default.jpg')}}" alt="">
				{% endif %}


			</div>
			{% if is_granted('ROLE_USER') and app.user.isVerified == 1 %}
				<div class="container-panel position-absolute">
					<div class="modify-panel ">
						<a href="{{path('modifyTrick',{slug:trick.slug})}}">
							<img class="icon white" src="{{asset('assets/img/svg/crayon.svg')}}">
						</a>

						<span class="open-modal" data-url={{path('deleteTrick',{slug:trick.slug} )}}>
							<img class="icon white" src="{{asset('assets/img/svg/trash.svg')}}">
						</span>

					</div>
				</div>

			{% endif %}
		</div>

		<div class="container">

			<div class="see_media btn-primary btn">
				See medias
			</div>

			<div class="no_see_media btn-primary btn">
				Hide medias
			</div>

			<div class="gallery">
				{% for image in images %}
					{% if loop.index != 1 %}
						<img src="{{asset('assets/img/tricks/mini/300x300-')}}{{image.name}}" alt="" srcset="">
					{% endif %}
				{% endfor %}


				{% for video in videos %}
					{{video.embed|raw}}
				{% endfor %}

			</div>

			<div class="description">
				{{trick.description}}
			</div>

			<div class="meta">

				{% if trick.trickGroup %}
					<div class="group-trick">
						group trick :
						{{trick.trickGroup.name}}
					</div>
				{% endif %}

				<div class="created-at">
					create at :
					{{trick.createdAt|date('d-M-Y')}}
				</div>

				{% if trick.createdAt != trick.modifiedAt %}
					<div class="modified-at">
						modified at :
						{{trick.modifiedAt|date('d-M-Y')}}
					</div>
				{% endif %}

			</div>

			<div class="comments-trick" id="comments-trick">


				{% if is_granted('ROLE_USER') and app.user.isVerified == 1 %}
					<div class="add_comment">
						{{ form_start(form) }}

						<div class="input">
							{{form_row(form.content)}}
						</div>

						<div class="input send">
							{{form_row(form.save)}}
						</div>

						{{ form_end(form) }}
					</div>
				{% endif %}

				<div class="h2_style text-center title">
					All Comments
				</div>

				<div class="d-flex flex-row flex-wrap comments">
					{% for comment in comments %}
						{% include "teasers/comment.html.twig" with {'comment' : comment} %}
					{% endfor %}


				</div>

				<div class="loader-container">

					<div class="inner-container">
						<span class="loader"></span>
						<div class="h2_style">Loading the following comments ...</div>
					</div>
				</div>


				<div class="btn btn-primary loadmore text_style" data-page="1" data-trick="{{trick.id}}" data-all-page="{{number_page}}">See more comments !
				</div>


			</div>

		</div>
		{% include 'component/modal.html.twig'%}
	</div>


{% endblock %}